### PR TITLE
Embedded records support

### LINKED ISSUE #1: Backgrounding for embedded models
Hi!
In mongoid you have another relation type: `embeds_one`/`embeds_many`+`embedded_in`.

This is an analog for `has_one`/`has_many`+`belongs_to`, but in case of embedding - embedded model will be saved as a nested JSON object inside it's parent object, instead of a standalone object (record) in separate collection ("table").

That's quite common practice to have embedded models in mongoid, and in most cases it totally makes sense to use this approach for some "Attachment" model.

But there is slight problem with that - it's **not possible** to find such embedded model using code like this: `Attachment.find(id)`.
Instead one should **find parent record first**, and then search for that attachment by its `id` inside parent's `attachments` collection, like this: `parent_record.attachments.find(id)`

So this means that the following code won't work:
```ruby
class TranscoderUploader < Shrine
  plugin :backgrounding
  Attacher.promote { |data| TranscodeJob.perform_async(data) }
end
```
Because the `data` hash contains data like this:
```ruby
{ ..., "record"=>["Attachment", "5bbb71b79bf2cc634c187a24"], ... }
```
So it actually tries to find attachment record like this: `Attachment.find('5bbb71b79bf2cc634c187a24')`, and we already know that won't work.

I got no idea how to make it work on this gem level "out of box", meanwhile I will try to come up with some workaround for this issue, and I will leave it here once I find it.

---
**UPDATE**
I meant that this code inside `TranscodeJob` won't work actually:
```
def perform(data)
    attacher = TranscoderUploader::Attacher.load(data)
    ...
end
```

So maybe that's not an issue at all, because it's my custom sidekiq job code is not working, not shrine's. I just was relaying on shrine's `Attacher.load` code, and now it's just not enough :)

### PR DESCRIPTION
**Pull request by flvrone**
[ partly resolves #1 ]

Hey @janko-m,

there are no tests for #swap yet, I was trying to figure out how to properly test it, but then I gave up, and decided to leave it to you.

And you're going to change those methods anyway, to achieve proper "overriding" and "order independency" in plugins inclusion.

And thanks for all your help with this, I probably wouldn't make it alone :)

### CODE REVIEW

**Comment by janko** [comment]
Had time to take a better look at this, and it looks great, very nice work! 👍 

I will try to merge this in the next few days and release a new version, then eventually I will fix Shrine so that we can lose the order dependency.

**Comment by flvrone** [comment]
Hey @janko-m, I've found a bug with `#swap` method, it's related to those nested attributes here #4.

If there are **few different embedded associations with files**, for some strange reason, not all of them could be "uploaded" using my workaround for nested attributes.

Everything works fine if I switch to this commit https://github.com/LinkUpStudioUA/shrine-mongoid/commit/2faf5f66468f1bc72062c526e8654b28d4b1da13, where `#swap` is not modified. (And backgrounding breaks of course :slightly_smiling_face:)

**Comment by flvrone** [comment]
Hey @janko-m,

I just realized that embedded records could be embedded into other embedded record, so embedding depth could be any, and this code currently supports only simplest scenario. So we should also cover those "recursive" embeds.

**Comment by flvrone** [comment]
OK, I've figured out what's the problem with `#swap` method.
You see, we have adapted it for `backgrounding` plugin, and when we do not use `backgrounding` - there will be no need in reloading, which is breaking everything.

I believe we have to check if `backgrounding` plugin is included and then use `#swap` method accordingly. (e.g. reload only when we deal with `backgrounding`).

**Comment by flvrone** [comment]
Added (I believe dirty) check for `backgrounding`, so now nested attributes are working properly for embedded models, if `cascade_callbacks` are enabled on association.

**Comment by janko** [comment]
@FunkyloverOne Thanks for updating. Sorry, I'm still keeping this PR in mind and it will definitely get merged, I just wasn't able to find time yet.

**Comment by flvrone** [comment]
@janko-m no problem, it still needs "recursive" embeds support to be implemented, so it's not finished anyway. I don't really have time for it just yet too.

**Comment by FunkyloverOne** [comment]
@janko-m no problem, it still needs "recursive" embeds support to be implemented, so it's not finished anyway. I don't really have time for it just yet too.

**Comment by janko** [comment]
@FunkyloverOne I'm impressed with your pull request, and I realized I'm not able to find time to properly review it. So I added you as a collaborator and gave you rubygems.org access, and you're free to merge the PR and push a new gem version if you want.

**Comment by janko** [comment]
Closing, as these changes won't be needed anymore in Shrine 3.0, see https://github.com/shrinerb/shrine-mongoid/issues/1#issuecomment-531529124.

**Pull request closed without merging**
